# Generated by Django 5.2.17 on 2026-09-21 22:50

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_doacao_latitude_doacao_longitude_alter_doacao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterField(
            model_name='doacao',
            name='foto',
            field=models.ImageField(blank=True, upload_to='doacoes_fotos/'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservada', 'Reservada'), ('coletada', 'Coletada'), ('a_caminho', 'A caminho'), ('entregue', 'Entregue'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], db_index=True, default='disponivel', max_length=20),
        ),
        migrations.AddIndex(
            model_name='doacao',
            index=models.Index(fields=['status', 'data_validade'], name='doacoes_doa_status_f30b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='doacao',
            index=models.Index(fields=['doador', 'status'], name='doacoes_doa_doador__a90893_idx'),
        ),
        migrations.AddIndex(
            model_name='doacao',
            index=models.Index(fields=['reservada_por', 'status'], name='doacoes_doa_reserva_6fc495_idx'),
        ),
    ]
